version: '3.4'

services:
  autonomous_ros2:
    image: autonomous

    build:
      context: .
      dockerfile: ./Dockerfile

    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      
      - ROS_DOMAIN_ID=47  # Its 47 for obvious reasons

    volumes:
      - .:/ws
      - /tmp/.X11-unix:/tmp/.X11-unix

    network_mode: host
    ipc: host
    stdin_open: true
    tty: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]