name: ✨✨✨Shiny new thing✨✨✨

description: ✨✨✨Request for a new shiny toy✨✨✨
title: "[✨FEAT✨]: "
labels: ["enhancement"]

body:
  - type: markdown
    attributes:
      value: |
        What is the new toy we want?

  - type: checkboxes
    id: new-toy
    attributes:
      label: Is there an existing enhancement request for this?
      description: Please search to see if a request already exists for this thing.
      options:
      - label: I have searched the existing feature requests
        required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a brief description of the feature or enhancement you would like
    validations:
      required: true

  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information on the feature request like proposed solutions, links, screenshots, etc.
