version: '3.4'

services:
  autonomous_ros2:
    image: autonomous

    build:
      context: .
      dockerfile: ../ros2_ws.Dockerfile

    environment:
      - DISPLAY
      - NVIDIA_VISIBLE_DEVICES=0
      - NVIDIA_DRIVER_CAPABILITIES=all
      
      - ROS_DOMAIN_ID=47  # Its 47 for obvious reasons

    volumes:
      - ..:/ws


    network_mode: host
    ipc: host
    stdin_open: true
    tty: true

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: []
              capabilities: [gpu]

  zed_sdk:
    image: stereolabs/zed:3.8-runtime-cuda11.7-ubuntu22.04