<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aruco_detection</name>
  <version>0.0.0</version>
  <description>This node detect aruco marker using zed2 node and opencv</description>
  <maintainer email="ych363@aucklanduni.ac.nz">yiyang</maintainer>
  <license>Apache License 2.0</license>
  
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>moa_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>geometry_msgs</exec_depend>

  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python-argparse</exec_depend>
  <exec_depend>python3-torch</exec_depend>
  

  <test_depend>ament_copyright</test_depend>
  <test_depend>ament_flake8</test_depend>
  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
