on:
  pull_request:
    branches:
      - main
      
jobs:
  build_test:
    name: Test if builds correctly
    runs-on: ubuntu-latest
    container:
      image: osrf/ros:humble-desktop
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Source ros2
        run: . /opt/ros/humble/setup.bash
        
      - name: rosdep install
        run: rosdep install --from-paths src -y --ignore-src
      
      - name: colcon build
        run: colcon build
      
