on:
  pull_request:
    branches:
      - main
      
jobs:
  build_test:
    name: Test if builds correctly
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install colcon
      run: sudo apt-get update && sudo apt-get install -y python3-colcon-common-extensions

    - name: Build workspace
      run: colcon build
      
